### ISSUE TITLE
Doesn't work with current stable Django (1.4)

### ISSUE THREAD

**Issue by taldcroft** [shimon/djangotutorial#1]
From the Django tutorial part 1:

The default project layout recently changed. If you're seeing a "flat" layout (with no inner mysite/ directory), you're probably using a version of Django that doesn't match this tutorial version. You'll want to either switch to the older tutorial or the newer Django version.

**Comment by trespitt** [comment]
Devs, can you please share what versions of python and django were used ?

**Comment by taldcroft** [comment]
Wow, time machine... This is long overtaken by events. Thanks for the offer to help, but I'm just closing this.
